# Generated by Django 4.2.7 on 2024-01-14 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_book_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READ", "Read"),
                            ("TO_READ", "To Read"),
                            ("READING", "Currently Reading"),
                            ("NOT_FINISH", "Did Not Finish"),
                            ("LIKED", "Liked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("review", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="bookauthor",
            name="author",
        ),
        migrations.RemoveField(
            model_name="bookauthor",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookcategory",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookcategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="bookrating",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookreview",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookshelf",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookuser",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookuser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bookuserrating",
            name="book_user",
        ),
        migrations.RemoveField(
            model_name="bookuserreview",
            name="book_user",
        ),
        migrations.RemoveField(
            model_name="bookusershelf",
            name="book_user",
        ),
        migrations.RemoveField(
            model_name="bookuserstatus",
            name="book_user",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="google_book_id",
            new_name="google_books_id",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="canonical_volume_link",
            new_name="preview_url",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="info_link",
            new_name="thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="book",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="book",
            name="image_links",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn_10",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn_13",
        ),
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.RemoveField(
            model_name="book",
            name="maturity_rating",
        ),
        migrations.RemoveField(
            model_name="book",
            name="page_count",
        ),
        migrations.RemoveField(
            model_name="book",
            name="preview_link",
        ),
        migrations.RemoveField(
            model_name="book",
            name="print_type",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="book",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="book",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="book",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="book",
            name="average_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(default="no description"),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="BookAuthor",
        ),
        migrations.DeleteModel(
            name="BookCategory",
        ),
        migrations.DeleteModel(
            name="BookRating",
        ),
        migrations.DeleteModel(
            name="BookReview",
        ),
        migrations.DeleteModel(
            name="BookShelf",
        ),
        migrations.DeleteModel(
            name="BookUser",
        ),
        migrations.DeleteModel(
            name="BookUserRating",
        ),
        migrations.DeleteModel(
            name="BookUserReview",
        ),
        migrations.DeleteModel(
            name="BookUserShelf",
        ),
        migrations.DeleteModel(
            name="BookUserStatus",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="userbook",
            name="book",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="books.book"),
        ),
        migrations.AddField(
            model_name="userbook",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
